name: "s3"

x-lockdown: &lockdown
  # prevents write access to the image itself
  read_only: true
  # prevents any process within the container to gain more privileges
  security_opt:
    - "no-new-privileges=true"

services:
  minio1:
    image: "11notes/minio:2025.10.15"
    hostname: "minio1"
    <<: *lockdown
    environment:
      TZ: "Europe/Zurich"
      MINIO_ROOT_CA_KEY_FILE: "/run/secrets/ca_key"
      MINIO_ROOT_CA_CRT_FILE: "/run/secrets/ca_crt"
      MINIO_ROOT_PASSWORD_FILE: "/run/secrets/password"
    command: "https://minio{1...2}/mnt/disk{1...2}"
    ports:
      - "3000:9001/tcp"
    volumes:
      - "minio1.ssl:/minio/ssl"
      - "/mnt/minio1:/mnt"
    tmpfs:
      # needed for read-only
      - "/run/secrets:uid=1000,gid=1000"
    secrets:
      - "ca_key"
      - "ca_crt"
      - "password"
    networks:
      frontend:
      backend:
    restart: "always"

  minio2:
    image: "11notes/minio:2025.10.15"
    hostname: "minio2"
    <<: *lockdown
    environment:
      TZ: "Europe/Zurich"
      MINIO_ROOT_CA_KEY_FILE: "/run/secrets/ca_key"
      MINIO_ROOT_CA_CRT_FILE: "/run/secrets/ca_crt"
      MINIO_ROOT_PASSWORD_FILE: "/run/secrets/password"
    command: "https://minio{1...2}/mnt/disk{1...2}"
    volumes:
      - "minio2.ssl:/minio/ssl"
      - "/mnt/minio2:/mnt"
    tmpfs:
      # needed for read-only
      - "/run/secrets:uid=1000,gid=1000"
    secrets:
      - "ca_key"
      - "ca_crt"
      - "password"
    networks:
      frontend:
      backend:
    restart: "always"

volumes:
  minio1.ssl:
  minio2.ssl:

networks:
  frontend:
  backend:
    internal: true

secrets:
  ca_key:
    file: "./ca.key.txt"
  ca_crt:
    file: "./ca.crt.txt"
  password:
    file: "./password.txt"